### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by garasubo** [mirage/mirage-block-xen#37] opened 2015-01-28 09:42 UTC
When I tried to install this package using opam, it failed as follow:
```
$ opam install mirage-block-xen
The following actions will be performed:
 - install mirage-block-xen.1.2.0
1 to install | 0 to reinstall | 0 to upgrade | 0 to downgrade | 0 to remove
The following variables are set in your environment, you should better unset it if you want OPAM to work correctly.
 - MIRAGE_OS
 - MIRAGE_NET
Do you want to continue ? [Y/n] y

=-=-= Installing mirage-block-xen.1.2.0 =-=-=
Building mirage-block-xen.1.2.0:
  make
  make install BINDIR=/home/garasubo/.opam/4.01.0/bin
[ERROR] The compilation of mirage-block-xen.1.2.0 failed.
Removing mirage-block-xen.1.2.0.
  make uninstall BINDIR=/home/garasubo/.opam/4.01.0/bin


===== ERROR while installing mirage-block-xen.1.2.0 =====
# opam-version 1.1.1
# os           linux
# command      make
# path         /home/garasubo/.opam/4.01.0/build/mirage-block-xen.1.2.0
# compiler     4.01.0
# exit-code    2
# env-file     /home/garasubo/.opam/4.01.0/build/mirage-block-xen.1.2.0/mirage-block-xen-8080-5f1023.env
# stdout-file  /home/garasubo/.opam/4.01.0/build/mirage-block-xen.1.2.0/mirage-block-xen-8080-5f1023.out
# stderr-file  /home/garasubo/.opam/4.01.0/build/mirage-block-xen.1.2.0/mirage-block-xen-8080-5f1023.err
### stdout ###
# ...[truncated]
# + /home/garasubo/.opam/4.01.0/bin/ocamlfind ocamlc -c -g -I lib -package cstruct -syntax camlp4o -package cstruct.syntax -package io-page -package lwt -syntax camlp4o -package lwt.syntax -package mirage-types -package mirage-xen -package shared-memory-ring -package shared-memory-ring.lwt -package xen-evtchn -package xen-gnt -package xenstore -syntax camlp4o -I lib -o lib/blkfront.cmo lib/blkfront.ml
# File "lib/blkfront.ml", line 507, characters 71-76:
# Error: This expression has type Cstruct.buffer list
#        but an expression was expected of type Io_page.t list
#        Type
#          Cstruct.buffer =
#            (char, Bigarray.int8_unsigned_elt, Bigarray.c_layout)
#            Bigarray.Array1.t
#        is not compatible with type Io_page.t 
# Command exited with code 2.
### stderr ###
# Makefile:7: config.mk: No such file or directory
# E: Failure("Command ''/home/garasubo/.opam/4.01.0/bin/ocamlbuild' lib/mirage_block_xen.cma lib/mirage_block_xen.cmxa lib/mirage_block_xen.a lib/mirage_block_xen.cmxs lib/mirage_block_xen_front.cma lib/mirage_block_xen_front.cmxa lib/mirage_block_xen_front.a lib/mirage_block_xen_front.cmxs lib/mirage_block_xen_back.cma lib/mirage_block_xen_back.cmxa lib/mirage_block_xen_back.a lib/mirage_block_xen_...[truncated]
# make: *** [build] Error 1

'opam install mirage-block-xen' failed.
```

The output of `opam list` as follow: 
```
Installed packages for 4.01.0:
base-bigarray             base  Bigarray library distributed with the OCaml compiler
base-bytes              legacy  Bytes compatibility library distributed with ocamlfind
base-no-ppx               base  A pseudo-library to indicate lack of extension points support
base-threads              base  Threads library distributed with the OCaml compiler
base-unix                 base  Unix library distributed with the OCaml compiler
camlp4                  4.01.0  Camlp4 is a system for writing extensible parsers for programming languages
cmdliner                 0.9.6  Declarative definition of command line interfaces for OCaml
conf-pkg-config            1.0  Virtual package relying on pkg-config installation.
cppo                     1.1.2  Equivalent of the C preprocessor for OCaml programs
crunch                   1.3.0  Convert a filesystem into a static OCaml module
cstruct                  1.5.0  access C structures via a camlp4 extension
io-page                  1.3.0  Allocate memory pages suitable for aligned I/O
ipaddr                   2.5.0  IP (and MAC) address representation library
lwt                      2.4.7  A cooperative threads library for OCaml
mirage                   2.2.0  The Mirage library operating system
mirage-block-unix        1.2.1  Mirage disk block driver for Unix
mirage-clock-unix        1.0.0  A Mirage-compatible Clock library for Unix
mirage-clock-xen         1.0.0  A Mirage-compatible Clock library for Xen
mirage-console           2.1.1  A Mirage-compatible Console library for Xen and Unix
mirage-profile             0.4  Collect profiling information
mirage-types             2.2.0  Module type definitions for Mirage-compatible applications
mirage-types-lwt         2.2.0  Lwt module type definitions for Mirage-compatible applications
mirage-unix              2.2.1  Mirage OS library for Unix compilation
mirage-xen               2.2.1  Mirage OS library for Xen compilation
mirage-xen-minios        0.6.0  Xen MiniOS guest operating system library
oasis                    0.4.5  Architecture for building OCaml libraries and applications
ocaml-data-notation     0.0.11  Store data using OCaml notation
ocaml-src               4.01.0  Compiler sources
ocamlfind                1.5.5  A library manager for OCaml
ocamlify                 0.0.1  Include files in OCaml code
ocamlmod                 0.0.7  Generate OCaml modules from source files
ocplib-endian              0.8  Optimised functions to read and write int16/32/64 from strings and bigarrays, based on new primitives added in version 4.01.
optcomp                    1.6  Optional compilation with cpp-like directives
ounit                    2.0.0  Unit testing framework loosely based on HUnit. It is similar to JUnit, and other XUnit testing frameworks
re                       1.2.2  RE is a regular expression library for OCaml
sexplib              111.25.00  Library for serializing OCaml values to and from S-expressions
shared-memory-ring       1.1.1  Shared memory rings for RPC and bytestream communications.
type_conv            111.13.00  Library for building type-driven syntax extensions
xen-evtchn               1.0.5  Xen event channel bindings.
xen-gnt                  2.2.0  Xen grant table bindings
xenstore                 1.2.5  Xenstore protocol clients and server
```

**Comment by djs55** [comment] 2015-01-28 11:22
I think the failure is caused by the recent interface change in
io-page.1.3.0 which has been released but the corresponding changes in
mirage-block-xen haven't been successfully tested and merged:

* https://github.com/mirage/mirage-block-xen/pull/36
* https://github.com/mirage/io-page/pull/16

As a temporary measure you could install the previous version of io-page
with a command like

```
opam install io-page.1.2.0
```


On Wed, Jan 28, 2015 at 9:42 AM, garasubo <notifications@github.com> wrote:

> When I tried to install this package using opam, it failed as follow:
>
> $ opam install mirage-block-xen
> The following actions will be performed:
>  - install mirage-block-xen.1.2.0
> 1 to install | 0 to reinstall | 0 to upgrade | 0 to downgrade | 0 to remove
> The following variables are set in your environment, you should better unset it if you want OPAM to work correctly.
>  - MIRAGE_OS
>  - MIRAGE_NET
> Do you want to continue ? [Y/n] y
>
> =-=-= Installing mirage-block-xen.1.2.0 =-=-=
> Building mirage-block-xen.1.2.0:
>   make
>   make install BINDIR=/home/garasubo/.opam/4.01.0/bin
> [ERROR] The compilation of mirage-block-xen.1.2.0 failed.
> Removing mirage-block-xen.1.2.0.
>   make uninstall BINDIR=/home/garasubo/.opam/4.01.0/bin
>
>
> ===== ERROR while installing mirage-block-xen.1.2.0 =====
> # opam-version 1.1.1
> # os           linux
> # command      make
> # path         /home/garasubo/.opam/4.01.0/build/mirage-block-xen.1.2.0
> # compiler     4.01.0
> # exit-code    2
> # env-file     /home/garasubo/.opam/4.01.0/build/mirage-block-xen.1.2.0/mirage-block-xen-8080-5f1023.env
> # stdout-file  /home/garasubo/.opam/4.01.0/build/mirage-block-xen.1.2.0/mirage-block-xen-8080-5f1023.out
> # stderr-file  /home/garasubo/.opam/4.01.0/build/mirage-block-xen.1.2.0/mirage-block-xen-8080-5f1023.err
> ### stdout ###
> # ...[truncated]
> # + /home/garasubo/.opam/4.01.0/bin/ocamlfind ocamlc -c -g -I lib -package cstruct -syntax camlp4o -package cstruct.syntax -package io-page -package lwt -syntax camlp4o -package lwt.syntax -package mirage-types -package mirage-xen -package shared-memory-ring -package shared-memory-ring.lwt -package xen-evtchn -package xen-gnt -package xenstore -syntax camlp4o -I lib -o lib/blkfront.cmo lib/blkfront.ml
> # File "lib/blkfront.ml", line 507, characters 71-76:
> # Error: This expression has type Cstruct.buffer list
> #        but an expression was expected of type Io_page.t list
> #        Type
> #          Cstruct.buffer =
> #            (char, Bigarray.int8_unsigned_elt, Bigarray.c_layout)
> #            Bigarray.Array1.t
> #        is not compatible with type Io_page.t
> # Command exited with code 2.
> ### stderr ###
> # Makefile:7: config.mk: No such file or directory
> # E: Failure("Command ''/home/garasubo/.opam/4.01.0/bin/ocamlbuild' lib/mirage_block_xen.cma lib/mirage_block_xen.cmxa lib/mirage_block_xen.a lib/mirage_block_xen.cmxs lib/mirage_block_xen_front.cma lib/mirage_block_xen_front.cmxa lib/mirage_block_xen_front.a lib/mirage_block_xen_front.cmxs lib/mirage_block_xen_back.cma lib/mirage_block_xen_back.cmxa lib/mirage_block_xen_back.a lib/mirage_block_xen_...[truncated]
> # make: *** [build] Error 1
>
> 'opam install mirage-block-xen' failed.
>
> The output of opam list as follow:
>
> Installed packages for 4.01.0:
> base-bigarray             base  Bigarray library distributed with the OCaml compiler
> base-bytes              legacy  Bytes compatibility library distributed with ocamlfind
> base-no-ppx               base  A pseudo-library to indicate lack of extension points support
> base-threads              base  Threads library distributed with the OCaml compiler
> base-unix                 base  Unix library distributed with the OCaml compiler
> camlp4                  4.01.0  Camlp4 is a system for writing extensible parsers for programming languages
> cmdliner                 0.9.6  Declarative definition of command line interfaces for OCaml
> conf-pkg-config            1.0  Virtual package relying on pkg-config installation.
> cppo                     1.1.2  Equivalent of the C preprocessor for OCaml programs
> crunch                   1.3.0  Convert a filesystem into a static OCaml module
> cstruct                  1.5.0  access C structures via a camlp4 extension
> io-page                  1.3.0  Allocate memory pages suitable for aligned I/O
> ipaddr                   2.5.0  IP (and MAC) address representation library
> lwt                      2.4.7  A cooperative threads library for OCaml
> mirage                   2.2.0  The Mirage library operating system
> mirage-block-unix        1.2.1  Mirage disk block driver for Unix
> mirage-clock-unix        1.0.0  A Mirage-compatible Clock library for Unix
> mirage-clock-xen         1.0.0  A Mirage-compatible Clock library for Xen
> mirage-console           2.1.1  A Mirage-compatible Console library for Xen and Unix
> mirage-profile             0.4  Collect profiling information
> mirage-types             2.2.0  Module type definitions for Mirage-compatible applications
> mirage-types-lwt         2.2.0  Lwt module type definitions for Mirage-compatible applications
> mirage-unix              2.2.1  Mirage OS library for Unix compilation
> mirage-xen               2.2.1  Mirage OS library for Xen compilation
> mirage-xen-minios        0.6.0  Xen MiniOS guest operating system library
> oasis                    0.4.5  Architecture for building OCaml libraries and applications
> ocaml-data-notation     0.0.11  Store data using OCaml notation
> ocaml-src               4.01.0  Compiler sources
> ocamlfind                1.5.5  A library manager for OCaml
> ocamlify                 0.0.1  Include files in OCaml code
> ocamlmod                 0.0.7  Generate OCaml modules from source files
> ocplib-endian              0.8  Optimised functions to read and write int16/32/64 from strings and bigarrays, based on new primitives added in version 4.01.
> optcomp                    1.6  Optional compilation with cpp-like directives
> ounit                    2.0.0  Unit testing framework loosely based on HUnit. It is similar to JUnit, and other XUnit testing frameworks
> re                       1.2.2  RE is a regular expression library for OCaml
> sexplib              111.25.00  Library for serializing OCaml values to and from S-expressions
> shared-memory-ring       1.1.1  Shared memory rings for RPC and bytestream communications.
> type_conv            111.13.00  Library for building type-driven syntax extensions
> xen-evtchn               1.0.5  Xen event channel bindings.
> xen-gnt                  2.2.0  Xen grant table bindings
> xenstore                 1.2.5  Xenstore protocol clients and server
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mirage/mirage-block-xen/issues/37>.
>



-- 
Dave Scott

**Comment by garasubo** [comment] 2015-01-29 08:13
After install the previous version of io-page, I can install mirage-block-xen. Thank you.

**Closed** 2015-02-27 04:09 UTC
